"""
# @filename    :  constants.py
# @author      :  Copyright (C) Church.ZHONG
# @caution     :  DO NOT MODIFY THIS FILE!
# @caution     :  DO NOT MODIFY THIS FILE!
# @caution     :  DO NOT MODIFY THIS FILE!
"""
################################################################
# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_LOOP_MAXIMUM_CYCLE_NUMBER_VIDEO = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_PHOTO = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_NIGHT = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_PANORAMA = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 1
META_LOOP_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 1

# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_ZOOM_MAXIMUM_CYCLE_NUMBER_VIDEO = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_PHOTO = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_NIGHT = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_PANORAMA = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 1
META_ZOOM_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 1

# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_HDR_MAXIMUM_CYCLE_NUMBER_VIDEO = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_PHOTO = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_NIGHT = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_PANORAMA = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 1
META_HDR_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 1

# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_REVERSE_MAXIMUM_CYCLE_NUMBER_VIDEO = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_PHOTO = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_NIGHT = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_PANORAMA = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 1
META_REVERSE_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 1

# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_FLASH_MAXIMUM_CYCLE_NUMBER_VIDEO = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_PHOTO = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_NIGHT = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_PANORAMA = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 1
META_FLASH_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 1

# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_VIDEO = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_PHOTO = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_NIGHT = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_PANORAMA = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 1
META_AIPORTRAIT_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 1

# 装饰器参数:表示打开相机后，单个元case循环的测试次数
META_STRESS_MAXIMUM_CYCLE_NUMBER_VIDEO = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_PHOTO = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_PORTRAIT = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_NIGHT = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_BURSTSHOT = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_FLASHSHOT = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_DUALSIGHT = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_TIMELAPSE = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_PANORAMA = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_SLOWMOTION = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_PROFESSIONAL = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_SPEEDWARP = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_ASTROPHOTO = 20
META_STRESS_MAXIMUM_CYCLE_NUMBER_ULTRASTEADYVIDEO = 20
################################################################
