"""
# @author      :  Copyright (C) Church.ZHONG
# @date        :  2024-04-08T16:09:59+08:00
"""

__version__ = "0.0.1"
__author__ = "Church ZHONG"

__all__ = [
    "set_pinchout",
    "set_pinchin",
    "click_center",
    "change_dropdown_settings",  # only export for validation
    "change_global_settings",  # only export for validation
    "toggle_dropdown_settings_by_key",  # only export for validation
    "set_dropdown_settings_by_key",  # only export for validation
    "toggle_global_settings_by_key",  # only export for validation
    "toggle_scan_qrcode",  # only export for validation
    "get_reverse",
    "set_zoom",
    "set_hdr",
    "set_reverse",
    "set_flash",
    "set_aiportrait",
    "set_beauty",
    "open_camera",
    "close_camera",
    "restart_camera",
    "warmup_camera",
    "setup_video",
    "take_video",
    "teardown_video",
    "setup_photo",
    "take_photo",
    "teardown_photo",
    "setup_portrait",
    "take_portrait",
    "teardown_portrait",
    "setup_night",
    "take_night",
    "teardown_night",
    "setup_burstshot",
    "take_burstshot",
    "teardown_burstshot",
    "setup_flashshot",
    "take_flashshot",
    "teardown_flashshot",
    "setup_dualsight",
    "take_dualsight",
    "teardown_dualsight",
    "setup_timelapse",
    "take_timelapse",
    "teardown_timelapse",
    "setup_panorama",
    "take_panorama",
    "teardown_panorama",
    "setup_slowmotion",
    "take_slowmotion",
    "teardown_slowmotion",
    "setup_professional",
    "take_professional",
    "teardown_professional",
    "setup_speedwarp",
    "take_speedwarp",
    "teardown_speedwarp",
    "setup_astrophoto",
    "take_astrophoto",
    "teardown_astrophoto",
    "setup_ultrasteadyvideo",
    "take_ultrasteadyvideo",
    "teardown_ultrasteadyvideo",
    "do_video",
    "do_photo",
    "do_portrait",
    "do_night",
    "do_burstshot",
    "do_flashshot",
    "do_dualsight",
    "do_timelapse",
    "do_panorama",
    "do_slowmotion",
    "do_professional",
    "do_speedwarp",
    "do_astrophoto",
    "do_ultrasteadyvideo",
    "do_album_view",
    "do_album_delete",
]

from .base import (
    set_pinchout,
    set_pinchin,
    click_center,
    change_dropdown_settings,  # only export for validation
    change_global_settings,  # only export for validation
    toggle_dropdown_settings_by_key,  # only export for validation
    set_dropdown_settings_by_key,  # only export for validation
    toggle_global_settings_by_key,  # only export for validation
    toggle_scan_qrcode,  # only export for validation
    get_reverse,
    set_zoom,
    set_hdr,
    set_reverse,
    set_flash,
    set_aiportrait,
    set_beauty,
    open_camera,
    close_camera,
    restart_camera,
    warmup_camera,
    setup_video,
    take_video,
    teardown_video,
    setup_photo,
    take_photo,
    teardown_photo,
    setup_portrait,
    take_portrait,
    teardown_portrait,
    setup_night,
    take_night,
    teardown_night,
    setup_burstshot,
    take_burstshot,
    teardown_burstshot,
    setup_flashshot,
    take_flashshot,
    teardown_flashshot,
    setup_dualsight,
    take_dualsight,
    teardown_dualsight,
    setup_timelapse,
    take_timelapse,
    teardown_timelapse,
    setup_panorama,
    take_panorama,
    teardown_panorama,
    setup_slowmotion,
    take_slowmotion,
    teardown_slowmotion,
    setup_professional,
    take_professional,
    teardown_professional,
    setup_speedwarp,
    take_speedwarp,
    teardown_speedwarp,
    setup_astrophoto,
    take_astrophoto,
    teardown_astrophoto,
    setup_ultrasteadyvideo,
    take_ultrasteadyvideo,
    teardown_ultrasteadyvideo,
)

from .camera import (
    do_video,
    do_photo,
    do_portrait,
    do_night,
    do_burstshot,
    do_flashshot,
    do_dualsight,
    do_timelapse,
    do_panorama,
    do_slowmotion,
    do_professional,
    do_speedwarp,
    do_astrophoto,
    do_ultrasteadyvideo,
)

from .album import do_album_view, do_album_delete
from .doubt import doubt_qrcode, doubt_portrait
